model:
  provider: "Qwen"
  name: "unsloth/Qwen2.5-0.5B-Instruct-bnb-4bit"
  load_in_4bit: True
  cache_dir: "./models"
  max_seq_length: 2048

training:
  epochs: 5
  batch_size: 2
  learning_rate: 0.00001
  # lr_scheduler: "cosine_with_restarts"
  # weight_decay: 0.01
  # warmup_ratio: 0.1
  
  # SFTTrainer args
  sft_config:
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 4
    warmup_steps: 10
    # max_steps calculated dynamically in script
    fp16: False # auto-detected
    bf16: True # auto-detected
    logging_steps: 1
    optim: "adamw_8bit"
    weight_decay: 0.01
    lr_scheduler_type: "linear"
    seed: 3407
    output_dir: "outputs"

  # LoRA config
  lora:
    r: 64
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    lora_alpha: 64
    lora_dropout: 0.5
    bias: "lora_only"
    use_gradient_checkpointing: "unsloth"
    random_state: 3407
    use_rslora: True
    loftq_config: null

# DPO Training Configuration
dpo_training:
  epochs: 2
  batch_size: 1
  gradient_accumulation_steps: 8
  warmup_steps: 5
  learning_rate: 0.0000005  # 5e-7 - much lower than SFT
  beta: 0.1  # DPO beta parameter for preference strength
  sft_model_path: "unsloth/Qwen3-0.6B-unsloth-bnb-4bit"  # Path to SFT model to load
